pub const IAM_LOGIN_FAILED: &str = "IAM_LOGIN_FAILED";
pub const IAM_CANNOT_AUTHENTICATE: &str = "IAM_CANNOT_AUTHENTICATE";
pub const IAM_PASSWORD_TOO_SHORT: &str = "IAM_PASSWORD_TOO_SHORT";
pub const IAM_ACCOUNT_REPOSITORY_ERROR: &str = "IAM_ACCOUNT_REPOSITORY_ERROR";
pub const IAM_TOKEN_GENERATOR_ERROR: &str = "IAM_TOKEN_GENERATOR_ERROR";
